### ISSUE TITLE
Admin can set transaction fees?

### ISSUE THREAD

**Issue by DaniellMesquita** [johnathanmartin/piWallet#10]

**Comment by johnathanmartin** [comment]
Please provide more details.

**Comment by DaniellMesquita** [comment]
Admin can set the transaction fee for sent coins?
Set fee and the receive address of admin to receive the fees.

**Comment by johnathanmartin** [comment]
The purpose of the wallet is not to make the administrator a profit. I would not support this but you may add it yourself to your own forked repository. Thank you.
