### ISSUE TITLE
Call to undefined function json_decode()

### ISSUE THREAD

**Issue by Original-Tasty** [johnathanmartin/piWallet#104]
Hi!

I've installed everything correctly, yet it won't let me login via the admin "piWallet"

It doesn't tell the password is incorrect, instead it simply does nothing. It refreshes the page and that's it.

Nothing in the logs regarding this issue

Anyone knows how to solve this?

Regards

**Comment by Original-Tasty** [comment]
Nevermind i was on 1604 instead of 1404

now getting new error though, changing title on the issue

**Comment by johnathanmartin** [comment]
apt-get install php5-json
