### ISSUE TITLE
Timezone wrong

### ISSUE THREAD

**Issue by MyGCoin** [johnathanmartin/piWallet#107]
Is there a way to set the correct time/ timezone? Transaction shows 9/23/2021 **04**:03 pm
when it should show 9/23/2021 **06**:03 pm

**Comment by johnathanmartin** [comment]
https://stackoverflow.com/questions/32224547/setting-the-timezone-for-php-in-the-php-ini-file
https://ubiq.co/tech-blog/how-to-change-default-timezone-in-apache-php/
