### ISSUE TITLE
blank page after login 

### ISSUE THREAD

**Issue by vpscoin** [johnathanmartin/piWallet#16]
just facing a problem when i install the script in online VPS and in my localhost too 
problem in my localhost :

```
Warning: fopen(http://...@**IPVPS**:**PORTRPC**/): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden in C:\xampp\htdocs\wallet\jsonRPCClient.php on line 133

Fatal error: Uncaught exception 'Exception' with message 'Unable to connect to http://**RPCUSER**:**RPCPASS**@**IPVPS**:**PORTRPC**/' in C:\xampp\htdocs\wallet\jsonRPCClient.php:141 Stack trace: #0 C:\xampp\htdocs\wallet\classes\Client.php(17): jsonRPCClient->__call('getbalance', Array) #1 C:\xampp\htdocs\wallet\classes\Client.php(17): jsonRPCClient->getbalance('zelles(piWallet...', 6) #2 C:\xampp\htdocs\wallet\index.php(22): Client->getBalance('piWallet') #3 {main} thrown in C:\xampp\htdocs\wallet\jsonRPCClient.php on line 141
```

problem in my online VPS ( i'm runing here the daemon of my coin algo x13
 i just follow all instructions when i try login with  piWallet and changeme its show blank page 
tried to create new user but the same problem 
http://my.vpscoin.org   check it here if you want 
dev if you are able to install this wallet in my vps i will donate to the project to develop it   also i'm ready to create custom template and improve arabic lang with right to left direction i'm a designer not developer :p
please need your help

**Comment by johnathanmartin** [comment]
Not meant to be ran on windows machines.

**Comment by vpscoin** [comment]
ok but how about my vps ubuntu 14.04 ? i install the wallet on it but showing blank page

**Comment by johnathanmartin** [comment]
Worked w/ @vpscoin to resolve this issue

**Comment by vpscoin** [comment]
10$ sent to @johnathanmartin  thank you so much for your help
https://blockchain.info/tx/7c299b65941fe7ffe0f9a79e181e34aa61b442e94b3da6b101e12220a48893a2

**Comment by cryptonana** [comment]
i face same issue how u fix this
