### ISSUE TITLE
2fa enabled by default?

### ISSUE THREAD

**Issue by viraladmin** [johnathanmartin/piWallet#17]
Trying to follow the install instructions from the wiki. The install was easy enough, but when I visit the page and try to log with user "admin" and password "changeme" but it keeps returning "Username, password or 2 factor is incorrect"

How do I know what the 2FA is? Is there a way to disable that until after admin is logged in?

**Comment by johnathanmartin** [comment]
My apologies, I might of forgot to update the wiki. Try to login with the username of piWallet and the password of changeme.

**Comment by johnathanmartin** [comment]
Just to follow-up on this, I've made the Wiki installation instructions much more clear now.
