### ISSUE TITLE
Blank page afer login only on some coins ? 

### ISSUE THREAD

**Issue by Findblocks** [johnathanmartin/piWallet#18]
as abouve some coins it works fine with and some it dont ? 

configs the same on all coins any ideas ?

**Comment by johnathanmartin** [comment]
We only officially support Sha and Scrypt. The white page indicates it can't connect with the database or coin daemon. Please enable PHP errors if you need more information on what's going on. Thank you.

**Comment by Findblocks** [comment]
the coins scrypt , but i think i found the problem ?

Its only the POS coins that give the white screen ? can you not stake with piwallet ? or is there anything i need to add to the coin config ? 

thanks for getting back to me 

Mark

**Comment by johnathanmartin** [comment]
Let me get back to you on this. I'm not 100% sure but I may have a few tricks up my sleeve. Send me an email.

**Comment by Findblocks** [comment]
will do thank you
