### ISSUE TITLE
White/Blank page after login or signup in POS coin

### ISSUE THREAD

**Issue by technoblitz** [johnathanmartin/piWallet#19]
White/Blank page after login or signup in POS coin

this is the error iam getting

**PHP Fatal Error: Uncaught Exception: Unable to connect to http://1:2@127.0.0.1:5445/ in /var/www/html/online/jsonRPCClient.php:141/nStack trace:\n#0 /var/www/html/online/classes/Client.php(17): jsonRPCClient->** 

i have tested with pow coin and it is working fine

**Comment by johnathanmartin** [comment]
The server is unable to connect with the daemon,please check config settings again and refrain from opening issues that are due to mis- configuration.

**Comment by technoblitz** [comment]
i have checked every thing , there is no mistake in config ,  because in the same files i have placed pow coin and tested and it works fine

**Comment by johnathanmartin** [comment]
We only officially support Scrypt and SHA coins with limited staking functionality.
