### ISSUE TITLE
POS coin connected. Address not generating..

### ISSUE THREAD

**Issue by malenchelon** [johnathanmartin/piWallet#20]
[error] [client 127.0.0.1] PHP Warning:  Invalid argument supplied for foreach() in /var/www/pi/view/wallet.php on line 93, referer: http://127.0.0.1/pi/
[error] [client 127.0.0.1] PHP Warning:  Invalid argument supplied for foreach() in /var/www/pi/view/wallet.php on line 120, referer: http://127.0.0.1/pi/

**Comment by johnathanmartin** [comment]
What version of PHP are you running?

**Comment by malenchelon** [comment]
php 5.6

**Comment by johnathanmartin** [comment]
Are you able to see previous transactions or balances after login?

**Comment by xviicoin-project** [comment]
Having this issue now myself... Anyone have any input?
