### ISSUE TITLE
Unauthorized user can access other people's coins. 

### ISSUE THREAD

**Issue by Tutakamimearitomomei** [johnathanmartin/piWallet#24]
Unauthorized users can access  and send other people coins in wallet

**Comment by mithrilda** [comment]
what exactly do you mean "Unauthorized users can access and send other people coins in wallet"

**Comment by johnathanmartin** [comment]
Please explan further

**Comment by cyberpay** [comment]
only admin can see coins /bal of each user yet he/she has to send coins from the total of all users. which would effect others balances.

**Comment by johnathanmartin** [comment]
No response from OP for a few months. I assume this issue is not valid.
