### ISSUE TITLE
Why does the Script display a Page 100% Blank after login?

### ISSUE THREAD

**Issue by garenfletch** [johnathanmartin/piWallet#25]
**Nothing appears after login. Right after you put the Admin login information (Username and Password). A 100% blank page with no information is displayed. Why, then, and how can I resolve this inconvenience?**

**Comment by justinvforvendetta** [comment]
@garenfletch because something isn't configured properly. check your apache logs ;]

**Comment by carsenk** [comment]
Usually that means you can't connect via jsonRPC, check your PHP Logs. There is a work around for this to either change over to easybitcoin.php or replace the code with curl instead of fopen. I unfortunately haven't had any luck connecting locally to an RPC daemon.

**Comment by justinvforvendetta** [comment]
@garenfletch @carsenk check /var/logs/apache2/error.log

should give you a reason for the problem. if you connect remotely, it can be pretty dangerous. if you want to post the error in your log here, go ahead.

**Comment by johnathanmartin** [comment]
Everyone here is right, make sure you've properly setup the database and the common.php file. You can also enable php debugging by adding this to the common.php file

`ini_set('error_reporting', E_ALL);
ini_set('display_errors', 'On');  //On or Off`
