### ISSUE TITLE
What is the Exact Version of Ubuntu that can run PiWallet successfully ???

### ISSUE THREAD

**Issue by chegmarco** [johnathanmartin/piWallet#26]
Hello dear friend.
  I would like to know which Ubuntu Exact Version do you use to run the PiWallet Script on your Personal Computer ???
I use the Ubuntu 16.04.2 LTS (Xenial Xerus) version.
 Is this also what you use ???
I ask that because I think the problem may be due to the System.
To be sure not to know any more problem that's why I ask you please specify the Ubuntu version you use to install and run piWallet at home without difficulty because piWallet has trouble working on Latest Version of Ubuntu (i.e: Ubuntu 16.04.2 LTS Xenial Xerus version) ???
 Thank you.

**Comment by justinvforvendetta** [comment]
any version can run it.

**Comment by chegmarco** [comment]
OK thanks for your answer.  But I have another problem after installing piWallet.
I think, it's been nearly a week now that I dig up what is causing the Bug that makes the PiWallet script (https://github.com/johnathanmartin/piWallet) still installed locally, can not generate new addresses. When you click on "Get a new Address", you should automatically see the Generated Address but I see that a problem still arises because no New Address is generated automatically but we see that even display the Message To Success (A new Adress was added to your wallet) but we do not see this address generated.

[https://i.imgur.com/Vfl0D3O.jpg](url)

This is also the case in the List of 10 Last Transactions (Date, Address, Type, Amount, Fee, Confs, Info) which is not displayed when a Transaction has been made.

So I wonder what is the basis of this problem. This is why I add to this message the Two (2) Files that contain the Generation of Addresses and Transactions so that you can see with me and help me correct this so that the Addresses and the Transaction List are displayed correctly As it should be.

Do you think that this error that causes the generated addresses not to appear are due to the fact that the Bitcoind Server has not yet fully synchronized ???

As explained on the site of Bitcoin of the Developer (https://en.bitcoin.it/wiki/PHP_developer_intro), it is necessary to completely leave the Bitcoind Server to download and synchronize. So do you think this is what is the basis of this error ?

**Comment by johnathanmartin** [comment]
Yes, make sure the bitcoind server is fully synchronised, and 12.04 will yield the best results. Please re-open if you are still having issues.
