### ISSUE TITLE
Is it necessary to initialize and synchronize Bitcoind to the server before running PiWallet ???

### ISSUE THREAD

**Issue by chegmarco** [johnathanmartin/piWallet#27]
I have problem after installing piWallet.
I think, it's been nearly a week now that I dig up what is causing the Bug that makes the PiWallet script still installed locally, can not generate new addresses. When you click on "Get a new Address", you should automatically see the Generated Address but I see that a problem still arises because no New Address is generated automatically but we see that even display the Message To Success (A new Adress was added to your wallet) but we do not see this address generated.

This is also the case in the List of 10 Last Transactions (Date, Address, Type, Amount, Fee, Confs, Info) which is not displayed when a Transaction has been made.

So I wonder what is the basis of this problem. This is why I add to this message the Two (2) Files that contain the Generation of Addresses and Transactions so that you can see with me and help me correct this so that the Addresses and the Transaction List are displayed correctly As it should be.

Do you think that this error that causes the generated addresses not to appear are due to the fact that the Bitcoind Server has not yet fully synchronized ???

As explained on the site of Bitcoin of the Developer (https://en.bitcoin.it/wiki/PHP_developer_intro), it is necessary to completely leave the Bitcoind Server to download and synchronize. So do you think this is what is the basis of this error ???

**Comment by johnathanmartin** [comment]
Yes
