### ISSUE TITLE
Blank page after signing in . Pos/pow Scrypt Coin

### ISSUE THREAD

**Issue by Aiden-aiden** [johnathanmartin/piWallet#30]
Hey :)
Firslty, I want to thank the dev for creating and sharing this web wallet for free :)

I install all dependencies (Php7) and configured and I've ran my daemon .
Here is the conf of my daemon coin : 

```rpcuser=aleph
rpcpassword=aleph123
rpcallowip=127.0.0.1
rpcport=21718
listen=1
server=1
txindex=1
daemon=1

accounts=1
staking=0```

And here is the debug file 
```
[Sat Aug 26 22:25:27.689851 2017] [:error] [pid 1683] [client 41.227.243.174:14866] PHP Fatal error:  Uncaught Exception: Unable to connect to http://aleph:aleph123@127.0.0.1:21718/ in /var/www/html/jsonRPCClient.php:141\nStack trace:\n#0 /var/www/html/classes/Client.php(17): jsonRPCClient->__call('getbalance', Array)\n#1 /va$
```

**Comment by johnathanmartin** [comment]
Responded via eMail:


PHP7 works best when using https://github.com/aceat64/EasyBitcoin-PHP to replace the current rpcfile. 

Please see http://imgur.com/a/LvYHy for implementation instructions - also please note that this is a hack of a job that I scraped together quickly. I suggest that you clean this file up.

After I've tested this enough, I'll make EasyBitcoin-PHP the main rpc file in piWallet.
