### ISSUE TITLE
Security Issue!!!

### ISSUE THREAD

**Issue by knkrth** [johnathanmartin/piWallet#31]
Hi, Is this wallet is secure for production use? Because there is a breach on https://deeponion.org/community/threads/onionwallet-has-been-tampered-with-hacked-this-morning.321/ As its simplicity anyone can use it. If its not secure or it is for educational purpose only please add a WARNING message on the READE.md to prevent the further risk.

**Comment by johnathanmartin** [comment]
piWallet is 100% secure and I urge you not to cause unnecessary panic, in the bitcoin talk thread - the owner of onionwallet's website has already admitted to not securing the Linux SSH server properly. But thank's for playing.

**Comment by johnathanmartin** [comment]
Please see https://bitcointalk.org/index.php?topic=2058630.msg20868491#msg20868491

& the lack of response to: https://bitcointalk.org/index.php?topic=2058630.msg20872928#msg20872928
