### ISSUE TITLE
Index.php keeps loading in loop after logging in

### ISSUE THREAD

**Issue by lanaiscool** [johnathanmartin/piWallet#35]
After i press login it keeps loading

**Comment by lanaiscool** [comment]
PHP Fatal error:  Uncaught exception 'Exception' with message 'Request error: Array' in /var/www/html/jsonRPCClient.php:156\nStack trace:\n#0 /var/www/html/classes/Client.php(17): jsonRPCClient->__call('getBalance', Array)\n#1 /var/www/html/classes/Client.php(17): jsonRPCClient->getBalance('zelles(piWallet...', 6)\n#2 /var/www/html/index.php(22): Client->getBalance('piWallet')\n#3 {main}\n  thrown in /var/www/html/jsonRPCClient.php on line 156
this is the error my coin uses getBalance instead of getbalance however i get an error when i change it to getBalance

**Comment by Aarti001** [comment]
i also get these same error....@lanaiscool

**Comment by Aarti001** [comment]
please help me about this error ..if u have any solution about these..

**Comment by lanaiscool** [comment]
Made my own web wallet to fix it

**Comment by Aarti001** [comment]
ok.....bur how .... @lanaiscool

**Comment by johnathanmartin** [comment]
This feature of Github is not for support, check your weblogs, hire a developer, check your config.
