### ISSUE TITLE
piWallet ( Backed have some "bugs" ) 

### ISSUE THREAD

**Issue by Aarti001** [johnathanmartin/piWallet#37]
Warning: fopen(http://...@127.0.0.1:3306/): failed to open stream: HTTP request failed! in C:\xampp\htdocs\piwallet-master2\jsonRPCClient.php on line 133

Fatal error: Uncaught exception 'Exception' with message 'Unable to connect to http://root:@127.0.0.1:3306/' in C:\xampp\htdocs\piwallet-master2\jsonRPCClient.php:141 Stack trace: #0 C:\xampp\htdocs\piwallet-master2\classes\Client.php(28): jsonRPCClient->__call('getaddressesbya...', Array) #1 C:\xampp\htdocs\piwallet-master2\classes\Client.php(28): jsonRPCClient->getaddressesbyaccount('zelles(admin)') #2 C:\xampp\htdocs\piwallet-master2\index.php(165): Client->getAddressList('admin') #3 {main} thrown in C:\xampp\htdocs\piwallet-master2\jsonRPCClient.php on line 141

please help us...

**Comment by johnathanmartin** [comment]
Duplicate, keeping #40 open
