### ISSUE TITLE
Fatal error: Uncaught exception 'Exception' with message 'Unable to connect to http://root:@127.0.0.1:3306/' 

### ISSUE THREAD

**Issue by Aarti001** [johnathanmartin/piWallet#39]
Fatal error: Uncaught exception 'Exception' with message 'Unable to connect to http://root:@127.0.0.1:3306/' in C:\xampp\htdocs\piwallet-master2\jsonRPCClient.php:141 Stack trace: #0 C:\xampp\htdocs\piwallet-master2\classes\Client.php(28): jsonRPCClient->__call('getaddressesbya...', Array) #1 C:\xampp\htdocs\piwallet-master2\classes\Client.php(28): jsonRPCClient->getaddressesbyaccount('zelles(admin)') #2 C:\xampp\htdocs\piwallet-master2\index.php(165): Client->getAddressList('admin') #3 {main} thrown in C:\xampp\htdocs\piwallet-master2\jsonRPCClient.php on line 141

**Comment by johnathanmartin** [comment]
Duplicate, keeping #40 open
