### ISSUE TITLE
Struggling to get the connection up 

### ISSUE THREAD

**Issue by izakhearn** [johnathanmartin/piWallet#41]
This is the error i get when trying to login 
```
Warning: fopen(http://...@127.0.0.1:1007/): failed to open stream: HTTP request failed! in /var/www/html/jsonRPCClient.php on line 133

Fatal error: Uncaught exception 'Exception' with message 'Unable to connect to http://keetirpc:HSZhSpCiU1PTAPbtkLfyxsg9mz8WpoWyoFWNmZkRiAQj@127.0.0.1:1007/' in /var/www/html/jsonRPCClient.php:141 Stack trace: #0 /var/www/html/classes/Client.php(17): jsonRPCClient->__call('getbalance', Array) #1 /var/www/html/classes/Client.php(17): jsonRPCClient->getbalance('zelles(piWallet...', 6) #2 /var/www/html/index.php(22): Client->getBalance('piWallet') #3 {main} thrown in /var/www/html/jsonRPCClient.php on line 141
```

**Comment by lpninja** [comment]
I am not sure how to login on the first time. Do I make a new account or do I use the official username: piWallet password:changeme and leave the 2FA part blank?
Many thanks.

**Comment by theSocialPoint** [comment]
any luck?

**Comment by lpninja** [comment]
How did it go?

**Comment by izakhearn** [comment]
It went great actually is running great with the new private crypto. Just wish i could scan the barcode it generate from within the webpage on my phone

**Comment by johnathanmartin** [comment]
This feature is not for support, but for reporting issues inside of piWallet itself. Check your logs, check your config, check the wiki setup, hire a developer. 

@izakhearn Try to install php-gd (That should get it working)
