### ISSUE TITLE
Use in coin without rpc_user

### ISSUE THREAD

**Issue by coinchangemarket** [johnathanmartin/piWallet#42]
Hello, I am trying to use this wallet for my currency but my currency does not have rpc_user or rpc_passsword. The currency is based on this https://github.com/cryptonotefoundation/cryptonote. Can someone help me?

I receive this error.

> Warning: fopen(http://.@127.0.0.1:34888/): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in /var/www/html/jsonRPCClient.php on line 133
> 
> Fatal error: Uncaught exception 'Exception' with message 'Unable to connect to http://:@127.0.0.1:34888/' in /var/www/html/jsonRPCClient.php:141 Stack trace: #0 /var/www/html/classes/Client.php(17): jsonRPCClient->__call('getbalance', Array) #1 /var/www/html/classes/Client.php(17): jsonRPCClient->getbalance('zelles(piWallet...', 6) #2 /var/www/html/index.php(22): Client->getBalance('piWallet') #3 {main} thrown in /var/www/html/jsonRPCClient.php on line 141

**Comment by johnathanmartin** [comment]
All "legitimate" coins have RPC credentials if you set it up the correct way. Also, the issues tab on github is for issues or bugs with piWallet, not with the coin itself, or for general support.
