### ISSUE TITLE
White screen after logging

### ISSUE THREAD

**Issue by bernatixer** [johnathanmartin/piWallet#45]
I'm trying to setup piWallet, but i'm facing a white screen after logging, as the Debugging section says, this could be because of a bad configuration of the RPC login, however I don't know what values to put.

My coin is based in Forknote, a fork of Bytecoin.
Thanks.

**Comment by johnathanmartin** [comment]
Check your logs, check your config. This feature of github is not for support, but for reporting issues in piWallet itself.
