### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by node1coza** [johnathanmartin/piWallet#47]
Hi
I am trying to set up on a linux server and the coin daemon runs as root. The web server user has no permission to access the service. How do I run my daemon as a user in an isolated group so that the website can talk to the daemon?
Regards
John

**Comment by johnathanmartin** [comment]
The daemon shouldn't run as root, but even if it is, that will not affect piWallet's ability to connect. Please verify the settings.php (or common.php in older versions) and the coin.conf file.
