### ISSUE TITLE
BUG, overdraft the transaction fee.

### ISSUE THREAD

**Issue by 9cat** [johnathanmartin/piWallet#5]
![image](https://cloud.githubusercontent.com/assets/1379110/7527960/3dfa7230-f4d6-11e4-9e5b-fc86bfd04a24.png)
BUG, overdraft the transaction fee.

**Comment by johnathanmartin** [comment]
Yes, This is a common issue with the coin client when you withdraw all your coins with a fee. I will look for a fix for this. Thank you.

**Comment by johnathanmartin** [comment]
As long as piWallet directly withdraws from the coin daemon there is no way to prevent this at this time.

**Comment by johnathanmartin** [comment]
Just thought of a solution to fix this. I will be Adding a reserve to withdraws to prevent over withdrawing the fee. Thank you.

**Comment by iquidus** [comment]
any updates on this?
thanks,

**Comment by johnathanmartin** [comment]
Nope, Still lagging behind with this. Have been extremely busy with school. Hope to get to it soon!

**Comment by johnathanmartin** [comment]
Okay, now it's really really fixed. The reserve works beautifully.

**Comment by yepcash** [comment]
Hey Jonathan how to add multiple currencies?

**Comment by johnathanmartin** [comment]
@yepcash One, this is not an issue. 2) it's not related to the current issue. 3) It's not a feature we offer. Please do not comment on any further issues.

**Comment by yepcash** [comment]
Hey Johnathan,

I have installed piwallet and want to use for clamcoins ... when trying to login it shows only blank page... can you help?

Thanks

On 17-Oct-2017, at 22:36, Johnathan Martin <notifications@github.com<mailto:notifications@github.com>> wrote:


@yepcash<https://github.com/yepcash> One, this is not an issue. 2) it's not related to the current issue. 3) It's not a feature we offer. Please do not comment on any further issues.
