### ISSUE TITLE
login index page problem

### ISSUE THREAD

**Issue by miacoin** [johnathanmartin/piWallet#50]
Warning: fopen(http://...@127.0.0.1:32486/): failed to open stream: HTTP request failed! HTTP/1.0 401 Authorization Required in /var/www/html/jsonRPCClient.php on line 133

Fatal error: Uncaught exception 'Exception' with message 'Unable to connect to http://rpc_miacoin:e22a9dcd30514eeb20892ecd7@127.0.0.1:32486/' in /var/www/html/jsonRPCClient.php:141 Stack trace: #0 /var/www/html/classes/Client.php(17): jsonRPCClient->__call('getbalance', Array) #1 /var/www/html/classes/Client.php(17): jsonRPCClient->getbalance('zelles(davide1)', 6) #2 /var/www/html/index.php(22): Client->getBalance('davide1') #3 {main} thrown in /var/www/html/jsonRPCClient.php on line 141

**Comment by leoclark2121** [comment]
Was this ever fixed? If yes, then how was it fixed?

I have tried everything within my reach and I still can not get it to work!

I need help with this, please.

**Comment by miacoin** [comment]
I can help you write me a detailed description of the problem, it's a while that I do not work there

**Comment by miacoin** [comment]
He did it to me too, send me the the setting file with your personal date not visible ,the problem is there

**Comment by leoclark2121** [comment]
Hi, for a few days now, I have been looking for a way to send you the file. Is there something like "private message" here?

**Comment by miacoin** [comment]
put your setting file here
