### ISSUE TITLE
CryptoCoin class error

### ISSUE THREAD

**Issue by apollygon** [johnathanmartin/piWallet#51]
```

( ! ) Fatal error: Class 'CryptoCoin' not found in /var/www/wallet/classes/Client.php on line 10
--


1 | 0.0000 | 231608 | {main}( ) | .../index.php:0
2 | 0.0005 | 265112 | Client->__construct( ) | .../index.php:19

```
installed a few times before, time before but first time with POS coin and tried two POS coins resulting in exact same error. Steps are all correct.

**Comment by johnathanmartin** [comment]
are you using php7?

**Comment by apollygon** [comment]
Hi, no 5.6. i tried with 5 & 7 also. same error thrown.

**Comment by johnathanmartin** [comment]
I'm quite confused why it's referring to the class 'CryptoCoin' as this isn't in piWallet itself. Do you mind sharing lines 8-11 with me of the /var/www/wallet/classes/Client.php file?

**Comment by johnathanmartin** [comment]
Didn't mean to close.

**Comment by johnathanmartin** [comment]
Still waiting to hear back.

**Comment by johnathanmartin** [comment]
closed due to non-response
