### ISSUE TITLE
Not Working with hybrid pos / pow coin

### ISSUE THREAD

**Issue by heginbotham1** [johnathanmartin/piWallet#55]
Hello, 
The coin I am trying to use is not working with this wallet for some reason it is a hybrid pos/ pow coin called LyraCoin and I get a white screen and It should be connecting to both mysql and rpc.

**Comment by johnathanmartin** [comment]
This form is for issues with the source code itself, not with the individual setup. Please consult https://FitTechHosting.com/cryptocurrency for hosted options, or review the server logs and follow the setup guide found in the Wiki.
