### ISSUE TITLE
White Screen After Login

### ISSUE THREAD

**Issue by t0itle** [johnathanmartin/piWallet#58]
Alright got to the point of signing in.
Obviously have done something right here but think it may be issue with sql?
Was pretty unclear for debug "uncomment first three lines" where?
Hit me at Brandt@rem.consulting would love to talk more

**Comment by johnathanmartin** [comment]
Uncomment the first three lines in common.php to enable debugging and post the result here.

**Comment by t0itle** [comment]
ok I so I went through double checked rpc and just get a spinning wheel when I log in. No debug errors

**Comment by CryptoBeginner** [comment]
Hi johnathanmartin. Im having this issue with Fatal error: Class 'Mysqli' not found in /var/www/html/index.php on line 5 
after debuging the 3 line  in common.php

PHP ver under 
root@chain:/var/www/html# dpkg -l | grep php| awk '{print $2}' |tr "\n" " "
libapache2-mod-php5.6 php-common php5.6 php5.6-cli php5.6-common php5.6-gd php5.6-json php5.6-mysql php5.6-opcache php5.6-readline root@openchain:/var/www/html# 

using ubuntu 16.04

**Comment by CryptoBeginner** [comment]
Warning: fopen(http://...@192.168.1.242:4412/): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error in /var/www/html/jsonRPCClient.php on line 133

Fatal error: Uncaught exception 'Exception' with message 'Unable to connect to http://multichainrpc:AJbptmgs4D3Td7oLGUpG1Q4rYNEp1p9UZj7s781pGgYe@192.168.1.242:4412/' in /var/www/html/jsonRPCClient.php:141 Stack trace: #0 /var/www/html/classes/Client.php(17): jsonRPCClient->__call('getbalance', Array) #1 /var/www/html/classes/Client.php(17): jsonRPCClient->getbalance('zelles(verron)', 6) #2 /var/www/html/index.php(22): Client->getBalance('verron') #3 {main} thrown in /var/www/html/jsonRPCClient.php on line 141

Im using Multichain Node using bitcoin setting blockhain
https://www.multichain.com/developers/creating-connecting/


rpcuser=multichainrpc
rpcpassword=xxxxxxxxxxxxxxxxx
rpcport=4412
rpcallowip=192.168.1.243

**Comment by johnathanmartin** [comment]
add enableaccounts=1 to the config.

**Comment by johnathanmartin** [comment]
Checking in on this again.

**Comment by johnathanmartin** [comment]
Closed as no response & duplicate

**Comment by t0itle** [comment]
Yo wtf....this isnt resolved...and not a duplicate seperate issue



Sent via the Samsung Galaxy S7 active, an AT&T 4G LTE smartphone


-------- Original message --------
