### ISSUE TITLE
Question on LTC and DOGE...

### ISSUE THREAD

**Issue by geopayme** [johnathanmartin/piWallet#6]
I visited your website and I was not able to create an account on LTC or DOGE. I get a blank screen.

Otherwise I like your idea.

Can you clarify abit on the altcoin option implementation?

**Comment by johnathanmartin** [comment]
I'm sorry, I am retiring the online site as it was not used too often. No one had a balance of more than $0.05 worth of coins. 

Any altcoin using Scrypt or SHA should work seamlessly with piWallet just by changing the config options in common.php

I'd be more than happy to discuss any questions you have at jmartin@fitbobcat.com

**Comment by geopayme** [comment]
Thank you for your reply Johnathan, I like your idea, I'll keep in touch
with you via the email you send me.

Here is my latest effort. Still learning about cryptos,
https://play.google.com/apps/testing/com.mygeopay.wallet

Do you do work for hire? PHP/Javascript

Cheers

Adonis

On Mon, Aug 31, 2015 at 10:20 PM, Johnathan Martin <notifications@github.com
> wrote:

> Closed #6 <https://github.com/johnathanmartin/piWallet/issues/6>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/johnathanmartin/piWallet/issues/6#event-397019705>.
>



-- 
Geopay.me Inc.

*"don't need to know everything, I just need to know where to find it."**A.
Einstein.*
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorised copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender therefore does not accept
liability for any errors or omissions in the contents of this message
which may arise as a result of email transmission.

**Comment by johnathanmartin** [comment]
Yes I do, however with school starting I will have no where near as much time for long projects. However feel free to shoot me a message if you run into a road block.
