### ISSUE TITLE
Send from self to self is possible?

### ISSUE THREAD

**Issue by leegod** [johnathanmartin/piWallet#61]
If I install this web wallet to some VPS (says, V), 

Lets say there run some coin wallet program, admin user A have pre-mined coin like 10,000,000.

Now after install web wallet to this same VPS, if many users make account here, can A send coin to user B?

Then this become self wallet send to self? Is this has no problem? 

And each user's address can only use his own address's balance?

**Comment by johnathanmartin** [comment]
That shouldn't be a problem at all. And yes, all user funds are secluded.
