### ISSUE TITLE
Are there no delete address button?

### ISSUE THREAD

**Issue by leegod** [johnathanmartin/piWallet#62]
Are there no delete address button?

**Comment by johnathanmartin** [comment]
https://bitcointalk.org/index.php?topic=1327.msg15136#msg15136

To quote Satoshi, "You should never delete a wallet."

**Comment by leegod** [comment]
Why I should never delete a wallet address?

**Comment by regtable** [comment]
> 
> 
> Why I should never delete a wallet address?

because yo never know when a hardfork will replenish your now empty private key. or when someone is willing to pay you for said empty key to make an attack :-)
