### ISSUE TITLE
How to setup this on real Bitcoin?

### ISSUE THREAD

**Issue by leegod** [johnathanmartin/piWallet#65]
I run a bitcoin daemon on my server. 

How can I set piwallet for use this web features? 

If piwallet is installed at another server with bitcoin daemon, then how?

**Comment by johnathanmartin** [comment]
I'm sorry this forum is for issues, not for support. For managed piWallet instances please consult http://fittechhosting.com/cryptocurrency or follow the setup guide in the wiki.
