### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by t0itle** [johnathanmartin/piWallet#66]
Fatal error: Unsupported operand types in /var/www/html/index.php on line 23

Ok So I got here...but now what?....

**Comment by justluce** [comment]
What’s on line 23?

**Comment by t0itle** [comment]
$resbalance = $client->getBalance($user_session) - $reserve;

**Comment by t0itle** [comment]
I believe 0



Sent via the Samsung Galaxy S7 active, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by justluce** [comment]
Set it to something other then 0. Otherwise, I don't know what will happen when it tries to make a transaction.

**Comment by justluce** [comment]
As the transaction fee is deducted from the reserve.

**Comment by t0itle** [comment]
Ohhhhh...so do I put coin in the wallet file?



Sent via the Samsung Galaxy S7 active, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by justluce** [comment]
Sure.

**Comment by t0itle** [comment]
ok tried making reserve something other than 0, didnt work.
Tried making sure there was coin actually in the wallet to use. nope
When rpc gets connection from web browser it is not being access from the right port? it says its coming from port 43110 instead of the port I picked

**Comment by t0itle** [comment]
ok. Changing the reserve to 100000 because that is my minimum fee. Mining enough coin to place there to test

**Comment by justluce** [comment]
What coin are you using?

**Comment by johnathanmartin** [comment]
Are you using php5, apache2? What does your coin.conf file look like? You didn’t answer my questions in the other issue you opened.

**Comment by t0itle** [comment]
Cryptonote based



Sent via the Samsung Galaxy S7 active, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by johnathanmartin** [comment]
If you’re going to refuse to answer my questions or follow my advice I’m afraid none of us will be able to help you. 

Also, I’ll remind you that the issues tab is not for support.

**Comment by t0itle** [comment]
Ok. Its not an issue...its a fatal error. Im just trying to figure your system out. I didnt see the question



Sent via the Samsung Galaxy S7 active, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by t0itle** [comment]
just email me and close this. I dont mind paying for the consultation. Just hit me up. I have emailed a few times
