### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by cryptodesigner** [johnathanmartin/piWallet#67]
Warning: Invalid argument supplied for foreach() in   -   pi/view/wallet.php on line [93](https://github.com/johnathanmartin/piWallet/blob/46eecc0bf16a135b2332f58a0bb31f638714fea5/view/wallet.php#L93)

Warning: Invalid argument supplied for foreach() in   -   pi/view/wallet.php on line [119](https://github.com/johnathanmartin/piWallet/blob/46eecc0bf16a135b2332f58a0bb31f638714fea5/view/wallet.php#L119)

![screenshot of creamcoin wallet](https://user-images.githubusercontent.com/37045747/39951734-0fcc64c0-558d-11e8-9e61-11e47dac32ec.png)

No addresses shown, no qr code.
Any suggestion ?

**Comment by johnathanmartin** [comment]
Run the 'getinfo' command for the daemon in the terminal and share the results

run 'getbalance piwallet' too

**Comment by cryptodesigner** [comment]
_Result for both (getinfo and getbalance) in terminal is:_
"balance" : 0.00000000,
