### ISSUE TITLE
Negative amount of coins

### ISSUE THREAD

**Issue by GYovchev** [johnathanmartin/piWallet#70]
Hi. I used from some hours piWallet and then the balance stopped updating. I was sending bitcoins to it but only the transactions was updating(after getting confirmations). I will give you some screenshots.
![last10](https://user-images.githubusercontent.com/16246199/40186113-f5d8a37a-59fc-11e8-8991-90748d6e82e2.png)
That are the transactions. We can see that the amount should be 1.16869758 coins.
But is is: 
![balance](https://user-images.githubusercontent.com/16246199/40186150-1438a8c4-59fd-11e8-9d07-9583c9418b75.png) Negative..

**Comment by johnathanmartin** [comment]
Have you set a minimum balance reservoir in the settings file?

**Comment by johnathanmartin** [comment]
Please set a minimum reservoir, this should resolve any issues.

**Comment by GYovchev** [comment]
No. This was not the problem. When I check my address amount form bitcoin-cli it was showing the real value. After 1-2 days when i opened your wallet again it was showing the correct value too. I think there is a bug

**Comment by GYovchev** [comment]
No. This was not the problem. When I check my address amount form  bitcoin-cli it was showing the real value. After 1-2 days when i opened  your wallet again it was showing the correct value too. I think there is a bug.

**Comment by johnathanmartin** [comment]
piWallet pulls the balance directly from the daemon.

**Comment by GYovchev** [comment]
I know, but I know what I saw too. 2 days later piwallet worked fine. I haven't change anything
