### ISSUE TITLE
Google 2FA - Listed as "Wallet"

### ISSUE THREAD

**Issue by Plainkoin** [johnathanmartin/piWallet#75]
Hello,

Once 2FA is enabled and showing up in a long list of sites on whichever device one has.  The default name is "Wallet".  While a user can go in and manually edit the entry...

Is it possible to use the value from Settings.php, $fullname = "Example Coin", to translate over to the 2FA when scanning the QRC code, to show as "Example Coin Wallet"?  As you have that function running through the site already.

Thank you,  Love your work, it's an excellent online wallet.

**Comment by Plainkoin** [comment]
For now, manually edited User.php for: $qrcode=$this->getQRCodeGoogleUrl('Example Wallet', $secret);  
 But would be nice if possible to import either $fullname or $short from settings.php.  So not really an issue, but "enhancement"?  If it does not affect overall function of the wallet?  

Thank you!

**Comment by johnathanmartin** [comment]
Feel free to go ahead and submit the Pull Request, otherwise, I'll add this to my todo list.

**Comment by johnathanmartin** [comment]
Fixed in commit https://github.com/johnathanmartin/piWallet/commit/197433f230e6eb9e35e4f68c8ec40ce43c5c42f2
