### ISSUE TITLE
piwallet work with walletbuilders.com

### ISSUE THREAD

**Issue by cryptonana** [johnathanmartin/piWallet#76]
i configure every thing but always show blank page after login please help me for this i use walletbuilders.com daemon please reslove i will donate money to this project

**Comment by johnathanmartin** [comment]
piWallet will work with any Scrypt/SHA coin. Please follow the setup guide, the issues tab is for issues in the source code itself, not for support.

**Comment by cryptonana** [comment]
ok every thing is fine close
