### ISSUE TITLE
This thing is full of SQL injection vulnerabilities and other major security flaws

### ISSUE THREAD

**Issue by DominoTree** [johnathanmartin/piWallet#77]
It would take 5 minutes for any half-competent web developer to obtain a full database dump of any instance of this app, including the ones that you charge $15 a month for.

https://github.com/johnathanmartin/piWallet/blob/master/classes/User.php#L235

**Comment by DominoTree** [comment]
Oh shit there's a Google search that shows all of the public instances - https://www.google.com/search?q=%22Powered+by+piWallet%22+%22...or+create+a+new+account%22

**Comment by ryan-shaw** [comment]
You should also add that real_escape_string doesn't prevent some SQL injections - https://stackoverflow.com/questions/5741187/sql-injection-that-gets-around-mysql-real-escape-string

**Comment by johnathanmartin** [comment]
Please stop trying to induce panic for issues that don’t exist. md5 will be taken care of. If you do find any vulnerabilities, I urge you to open a new issue with the specifics. Thank you.

**Comment by DominoTree** [comment]
Did you even read my post?  Have you heard of SQL injection?

**Comment by DominoTree** [comment]
This has literally nothing to do with MD5.

**Comment by johnathanmartin** [comment]
No, I agree it definitely is. I’m just saying that it’s not a world ending flaw. It’s an enhancement that is on the todo list.
