### ISSUE TITLE
Lots of bugs

### ISSUE THREAD

**Issue by cryptonana** [johnathanmartin/piWallet#81]
script have lots of bug some time 2fa auth working some time only load page and nathing show some time address qr show some time need to refresh page this is totaly useless script balance not show only refresh page so balance show and transcation show after refresh page

**Comment by johnathanmartin** [comment]
I’m having troubles understanding your very broken English. Do you mind trying to rephrase? I’m having troubles reproducing the required refresh issue. However, yes, it is a known issue that you have to login atleast once in the past to enable 2factor, that is documented inside the application.

**Comment by johnathanmartin** [comment]
No Response
