### ISSUE TITLE
API configuration

### ISSUE THREAD

**Issue by cryptonana** [johnathanmartin/piWallet#84]
i wana configure android wallet with pi wallet where i get API configuration???

**Comment by johnathanmartin** [comment]
There is currently no API, however, it wouldn't be too hard to build one - if that's not your style feel free to check out https://fittechhosting.com/cryptocurrency for android app solutions.

**Comment by cryptonana** [comment]
you say you doing android app $200one time but i see your android demo web wallet you convert to apk i dont want this, i have android source and i want API can you done API for me

**Comment by johnathanmartin** [comment]
Unfortunately not
