### ISSUE TITLE
Wallet not encrypted?

### ISSUE THREAD

**Issue by CryptorClub** [johnathanmartin/piWallet#85]
@johnathanmartin Nice work, I've enjoyed of speed and simpliest to use script!

How to use encrypted wallet?

**Comment by johnathanmartin** [comment]
This isn't an issue, and I'm not sure what you're asking.

**Comment by johnathanmartin** [comment]
You can change your password after you login with the default of piWallet/changeme.

**Comment by johnathanmartin** [comment]
Theres a button that says change password

**Comment by CryptorClub** [comment]
It's true. I talk about wallet.dat file from coind

**Comment by CryptorClub** [comment]
I talk about encrypting coin daemon. Or you think its not necessary?

**Comment by johnathanmartin** [comment]
I don't think it'd be possible. piWallet is a hot-wallet meaning that the daemon or coins themselves can not be encrypted.

**Comment by regtable** [comment]
i understand this is closed however to do the above you would need to implement an unlockwallet(password,timer) method to call every time a withdraw is needed to be made and it would leave the wallet open for withdraws for a specific period (timer in seconds) semi pointless but thought id mention it. a lot of work for securing against a breach to your root assuming it is hardened shouldnt be nescaserry
