### ISSUE TITLE
Sign up and login issue.

### ISSUE THREAD

**Issue by Crypto-Robin-Hood** [johnathanmartin/piWallet#98]
https://wallet.bitcoinrand.com/

Users can't login nor sign up.

**Comment by XVictus-project** [comment]
http://82.148.19.101/index.php

I have the same problem (System error), although 2 years ago I launched this web wallet. 
Maybe the source code has changed significantly.

If there is a solution, please reply here or by email
xvictus.project@gmail.com

**Comment by XVictus-project** [comment]
now i am getting error:

Undefined index: g-recaptcha-response in /var/www/html/index.php on line 312

**Comment by xcelr** [comment]
Having the same problem

**Comment by xcelr** [comment]
Did you find a fix?

**Comment by XVictus-project** [comment]
> Вы нашли исправление?

I can help you launch a web wallet
write to e-mail xvictus.project@gmail.com

my web wallet, I added invests
https://wallet.betller.io/

**Comment by xcelr** [comment]
Hey thanks for reaching out, i keep running that error of http 500 can't
connect. How did you get around this. Curl runs the commands fine and
connects to the prt everything adds up but when the actual piWallet script
runs it via JsonRPCphp it throws that error.

**Comment by totaltrader** [comment]
It is frustrating nightmare not able to login or sign-up.
I has been reinstaling several times but nothing
Anybody have solution for it?

**Comment by totaltrader** [comment]
> It is frustrating nightmare not able to login or sign-up.
> I has been reinstaling several times but nothing
> Anybody have solution for it?

Fixed
Make sure your google recaptcha is correct, if it is not correct script will not let you log in
check the install instructions at the end, to uncomment and debug your installation and you will see the errors.

**Comment by wattson-coder** [comment]
no problems with login or signup - works perfectly

**Comment by quenecia** [comment]
Hello,
I have same problem. When i try to sign up. I saw to 'system error' notification. Who can help me about that ?

**Comment by forking-altcoins** [comment]
> Hello, I have same problem. When i try to sign up. I saw to 'system error' notification. Who can help me about that ?

hi 
I can launch a web wallet for you with minor modifications.
not expensive at all ;)
example: https://wallet.betller.io/

**Comment by quenecia** [comment]
> > Hello, I have same problem. When i try to sign up. I saw to 'system error' notification. Who can help me about that ?
> 
> hi I can launch a web wallet for you with minor modifications. not expensive at all ;) example: https://wallet.betller.io/

Hello dude can you give me your mail?

**Comment by forking-altcoins** [comment]
> > > Hello, I have same problem. When i try to sign up. I saw to 'system error' notification. Who can help me about that ?
> > 
> > 
> > hi I can launch a web wallet for you with minor modifications. not expensive at all ;) example: https://wallet.betller.io/
> 
> Hello dude can you give me your mail?

forking.altcoins@gmail.com
